version: "3"
services:
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: branch_wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]
